### PR TITLE
Write bias register of vectornav 

### PR DESCRIPTION
**Pull request by rafa-martin**
Refactored the code into a class and added a feature to calibrate bias imu with service.
Added dev container to enhance development task.

### CODE REVIEW

**Comment by alvarovillena** [comment]
Given that this repo is a fork from another one, we should change the existing code as less as possible, in order to be able to merge future changes easily. This means that, even if the use of classes and separation between headers and body is a good practice, we should not do it in this specific situation.

The only goal of the PR should be adding the accelerometers bias calibration method. Please do it following the already existing structure.

**Review by alvarovillena — CHANGES_REQUESTED** [review]
Please read my previous comment regarding the requested changes.

**Comment by TheBerbat** [comment]
Updated main.cpp with calibration functionality. And solve bugs by taking samples.

**Comment by jmnavarrete** [comment]
It has been tested on a real robot and worked correctly. To calibrate automatically use the service: "/robot/vectornav/set_acc_bias".

**Review by alvarovillena — APPROVED** [review]
It seems to be working as expected :)

We will start using it in production now, so I'll merge it directly to speed up the process. However, as stated earlier, we don't really need the header, cpp and launch files. I understand that the new code is _better_, but we don't want to diverge from the upstream. Having multiple nodes and launch files may be confusing for new users.

**Pull request merged**
